project:
  type: book

book:
  title: "Conversion Algorithm for 3D Visualization of Material Grids of Zeolite Structures from ZeoGAN"
  author: 
    name: "Rhona X. Zhang"
  date: today
  date-format: iso
  downloads: [pdf, epub]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - intro.qmd
    - lit_review.qmd
    - methods.qmd
    - results.qmd
    - nxt_steps.qmd
    - references.qmd

nocite: |
  @*
bibliography: references.bib
# set style for bib
csl: apa.csl

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

