project:
  type: book

book:
  title: "Honors Thesis"
  author: "Rhona Zhang"
  date: today
  date-format: iso
  downloads: [pdf, epub]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - intro.qmd
    - lit_review.qmd
    - methods.qmd
    - results.qmd
    - references.qmd

bibliography: references.bib
# set style for bib
csl: apa.csl

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

