# Introduction {#sec-intro}

One of the most pressing issue facing the current global community is climate change and global warming, which has instigated discussion of concerns regarding current energy and fuel resources and research into solutions to the environmental crisis. Cutting-edge technology have enabled new discoveries and improvements on existing solutions to alleviate current environmental challenges. Progress in the Nanomaterials Science and new advancements in Machine Learning  have expedited developments and improvements in innovative methods of capturing greenhouse cases. 

Recent research points to prioritizing the capture, storage, and use of methane emissions as a potential solution to the fuel crisis. The removal of methane can lead to significant improvements in overall air quality and decreases in global warming since it is the second most abundant greenhouse gas and extremely potent in trapping heat [@jordan_removing_2021]. 

The combined risk factor associated with methane's high flammability and lack of existing research on methane capture and energy efficient conversions to fuel makes it challenging to safely work with. However, it offers promising potential to be a source of energy that surpasses other fossil fuels as a solution to the fuel crisis. Furthermore, significant removal of methane can lead to drastic decreases in overall global temperatures and the issue of global warming since methane is the direct contributor to an increase in the ozone layer [@jordan_removing_2021].

Zeolites, a class of crystalline, microporous inorganic solid consisting of silicon and oxygen atoms, offer a safe and reliable solution to storing and transporting methane and other volatile gases, such as carbon dioxide, without further emitting pollutants. They offer distinct advantages over other catalysts such as (1) being an inexpensive material, (2) relatively low energy and temperature required to capture gas, and (3) low risk and simple methadology. This study will use 234 zeolites from International Zeolites Association (IZA) experimental structures and 331,163 from Predicted Crystallography Open Database (PCOD) hypothetical zeolites [@kim_inverse_2020].

The research focuses on improving an existing algorithm for inorganic solids design of three dimensional material grids of atomic-scale structures of zeolites, ZeoGAN. ZeoGAN, or zeolite GAN, is an already existing generative adversarial network (GAN) model with the goal of generating new potential zeolites and energy shapes using artificial neural networks. The present research aims to improve this basic GAN model to allow users to develop zeolites with specific physical properties, such as zeolites with low energies, which means higher binding potentials to improve stable capture of methane particles. 

This can be accomplished by integrating HydraGNN as a function in ZeoGAN. HydraGNN is a pre-existing multi-tasking graph convolutional neural network model that predicts global and atomic physical properties given atomic structures. However, one primary barrier preventing an easy integration process is that HydraGNN requires input data to be in Cartesian format, but the output of ZeoGAN is the energy shapes of a materials' grid. 

Thus, the algorithm developed will be incorporated into the generative adversarial network, ZeoGAN, as a function for converting the crystal lattice data of the material grids into Cartesian coordinates for training of HydraGNN. Since the output of ZeoGAN is difficult to visualize, the algorithm also provides the data required to plot the 3D molecular structures to assess and confirms the accuracy of the material grids of the zeolite structures generated from ZeoGAN.
